# -*- coding: utf-8 -*-
"""ch02_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17saR4gYVzVlRGJttyaQUfMrnwcppaqD1
"""

!pip install numpy #R에서 설치같은 느낌

import numpy as np #R에서 라이브러리 같은 느낌

"""2.2 ndarray"""

#1차원
data1=[1,2,3,4]
arr1=np.array(data1)
print(arr1) #콤마 구분 없이 나온다
print(type(arr1)) #객체 타입이 ndarray

#2차원
data2=[
    [1,2],
    [3,4]
]
arr2=np.array(data2) #안에 리스트 형태만 들어가야하는듯.
print(arr2)
print(type(arr2))
print(type(arr2[0]))

print(arr2.shape)
print(arr2.ndim) #차원
print(arr2.dtype)
print(arr1.shape) #한 개면 데이터길이

data =[
    [1],
    [2],
    [3],
    [4]
]
c=np.array(data)
print(c.shape)

print(np.zeros(3)) #0으로 채워진 ndarray return
print(np.ones(3)) #1로 채워진 리턴 #dot이 있다-> 타입이 실수이다.

size=(3,4) #(로우,칼럼)
print(np.zeros(size))

print(np.zeros((3,4)))

#arange
#파라미터 3개까지 입력 가능
print(np.arange(5)) #리스트 처럼. 0부터 5 전까지
print(np.arange(1,5)) #1부터 5전까지
print(np.arange(1,5,2)) #1부터 5전까지. 2개씩 증가

#reshape
ndarr1=np.arange(6)
ndarr2=ndarr1.reshape(2,3) #(로우, 칼럼)
print(ndarr2)

"""2.3 데이터 타입"""

arr=np.array([1,2,3],dtype=np.uint8)
print(arr.dtype)
print(arr.dtype.kind) #축약
print(arr.dtype.alignment) #1바이트 단위= 8비트

#타입 변경 astype
arr=arr.astype('int8')
print(arr.dtype)

#데이터 타입 변경 할 때 범위 주의
a=np.array([0,255],dtype=np.uint8)
b=a.astype('int8')
print(a)
print(b)

#높은 비트=높은 정밀도 #그치만 저장공간까지 고려해야함
a16=np.array([1.333333],dtype=np.float16)
a32=np.array([1.333333],dtype=np.float32)
print(a16)
print(a32)

#무한 소수
a16=np.array([1.0],dtype=np.float16)
a32=np.array([1.0],dtype=np.float32)
print(a16/3)
print(a32/3)

#무한대와 결측치 ->float
print(np.nan, type(np.nan))
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

arr=np.array([-1,2,-3])
print(arr/0)
print(arr+np.nan)
print(arr+np.inf)

"""2.4 인덱싱과 슬라이싱"""

arr=np.arange(4)
print(arr[0])

arr=np.arange(4).reshape(2,2)
print(arr[0]) #row에 우선 적용

print(arr[0][0]) #첫 행에서 첫 열. [로우][칼럼]. 로우 찾고->칼럼 찾는 방식
print(arr[0,0]) #[로우,칼럼] 으로도 할 수 있다. 튜플로 한 번에 찾아서 이 방법이 더 빠름

# Commented out IPython magic to ensure Python compatibility.
#실제로 시간을 비교해보자!
a=np.arange(10000).reshape(100,100)
# %timeit a[0,50]
# %timeit a[0][50]

#슬라이싱
arr=np.arange(4)
print(arr[:2]) #2번 위치 전까지.ndarray로 슬라이싱 됨.

#타겟팅
target=[0,2]
print(arr[target]) #0번 위치, 2번 위치 출력
print(arr[[0,2]]) #대괄호 중첩. 1. 슬라이싱 기호, 2. 리스트

#2차원 슬라이싱
arr=np.arange(20).reshape(4,5)
print(arr[:2])

#왼쪽 끝 두개 칼럼 슬라이싱
print(arr[:,:2]) #[로우 시작: 로우 끝, 칼럼 시작: 칼럼 끝]

print(arr[1:4,2:5])
print(arr[1:,2:])

"""2.5 브로드캐스팅"""

a=np.array([1,2,3])
b=np.array([2,3,4])
print(a+b)
print(a*b)
print(a%b)
print(a+3) #3이 shape(1.)에서 shape(3.)으로 a에 맞춰 확장
#연산이 ndarray로 확장 적용 = 브로드캐스팅.
#작은 크기의 ndarray가 큰 크기의 ndarray로 확장.

"""브로드 캐스팅 조건
1. 뒤 열의 길이가 같다.
EX) a:(3,2) b:(2,) =>열 확장(뒤부터 확인)-> 행 확장-> 연산
2. 비교하는 어느 한 열의 길이가 1이다.
EX) a:(3,1) b(2,) =>b 브로드 캐스팅 -> a 브로드 캐스팅 -> 연산
"""

high = [92700, 92400, 92100, 94300, 92300]
low= [90000, 91100, 91700, 92100, 90900]

arr_high=np.array(high)
arr_low=np.array(low)

arr_diff=arr_high-arr_low
print(arr_diff)

arr_high_x3 = arr_high *3 #3 브로드 캐스팅
arr_low_x2 = arr_low *2 #2 브로드 캐스팅
print(arr_high_x3 + arr_low_x2)

avg = (arr_high * 3) + (arr_low * 2)
print(avg)

data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)
print(arr[0] * 3 + arr[1] * 2)

weight = np.array([3,2]).reshape(2,1)
print((weight * arr).sum(axis=0)) #weight에 브로드캐스팅

"""2.6 조건 연산"""

#1
arr = np.array([10,20,30])
print(arr>10) #10 브로드캐스팅 되어서 비교됨.

#2
cond = [False, True, True]
print(arr[cond])

#3
print(arr[[False, True, True]])

#4
print(arr[[False, False, False]])

#5
cond = arr > 10
print(arr[cond])

#6
print(arr[arr > 10])

#7
print(cond.all())
print(cond.any())

#8
cond0 = arr > 10 #[False True True]
cond1 = arr < 30 #[True True False]
print(arr[ cond0 & cond1]) #[False True False]를 슬라이싱-> 가운데 위치 -> 20

#9
print(arr [(arr > 10) & (arr < 30)])

#10
arr = np.array([10, 20, 30])
cond = arr > 10
arr[cond] = 1 #조건 충족하는 데이터 선택해서 1로 업데이트
arr[~cond] = 0 #조건 충족하지 않는 데이터 선택해서 0으로 업데이트
print(arr)

#11
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, 1, 0) #R에서 if문법 느낌
print(arr)

#12
arr = np.array([10, 20, 30])
cond = arr > 10
arr[cond] = arr[cond] + 10
arr[~cond] = arr[~cond] - 10
print(arr)

#13
arr = np.array([10, 20, 30])
arr = np.where(arr > 10, arr+10, arr-10)
print(arr)

#예제
lge = np.array([93000, 82400, 99100, 81000, 72300])
print(len(lge[lge <= 85000]))

"""2.7 함수와 메서드"""

#전체 데이터 합
arr = np.arange(8).reshape(4,2)
print(arr.sum())

#축 정보 합
print(arr.sum(axis=0)) #axis=0 -> x축 방향 합
print(arr.sum(axis=1)) #axis=1 -> y축 방향 합

#min, max, mean, std(표준편차), var(분산) 메서드도 사용 가능하다.

#랜덤한 수 만들기
random1= np.random.randint(3) #0~2에서 랜덤한 수
print(random1)

#랜덤한 ndarray 만들기
random2 = np.random.randint(46, size=5)
print(random2)

random3 = np.random.randint(46,size=(2,5))
print(random3)

#linspace 함수
#(시작값, 종료 값, 분할 지점의 수)
x = np.linspace(0, 10, 3) #0부터 10까지 균등한 3개의 지점으로 분할
print(x)

#stack
#vstack 수직방향, hstack 수평방향
a = np.arange(4) #[0 1 2 3]
b = np.arange(4,8) #[4 5 6 7]

v = np.vstack([a,b])
print(v)

h = np.hstack([a,b])
print(h)