# -*- coding: utf-8 -*-
"""ch03_pandas-series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ki3LsMug-8xLnQzsjbgkmJDr5Rd6ATaH
"""

!pip install pandas

"""*   리스트: 순서 있고 수정 가능
*   튜플: 순서 있고 수정 불가능
*   딕셔너리: 키:벨류 쌍. 순서 없음 (인덱싱 불가능)

3.2 시리즈 생성
"""

from pandas import Series

data = [10, 20, 30]
s = Series(data) #시리즈 객체 생성하기 #대문자 주의
print(s)


#넘파이 이용하기
import numpy as np

data = np.arange(5)
s = Series(data)
print(s)


#문자열도 가능
#판다스에서 데이터 타입은 object
data = ["시가", "고가"]
s = Series(data)
print(s)

#타입 섞여도 object -> object는 브로드 캐스팅 불가능하다.
s = Series(['samsung', 81000])
print(s)


#인덱스는 RangeIndex

"""3.3 시리즈 인덱스"""

data = [1000, 2000, 3000]
s = Series(data)
print(s.index) #(시작, 끝, 증가량)
print(s.index.to_list()) #파이썬 리스트로 인덱스 값 변환

#인덱스 수정하기
s.index = ["메로나", "구구콘", "하겐다즈"]
print(s)

#생성할 때 같이 생성할 수도
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]

#방법1
s = Series(data, index)
print(s)

#방법2
s = Series(data=data, index=index) #keyword argument: 시리즈 객체를 생성할 때 파라미터 이름을 직접 지정
print(s)

v = [1000, 2000, 3000]
k = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=v, index=k)
print(s)
s = Series(v,k)
print(s)

s = Series(data, index)
s = Series(data, index = index) # 제일 많이 쓰는 방식인듯
s = Series(data=data, index=index)
s = Series(index=index, data=data)
s = Series(data = None, index= None) # None. 해당 값이 입력되지 않을 수도 있다. index없이 data만으로도 시리즈 생성 가능

#reindex
s2 = s.reindex(["메로나", "비비빅", "구구콘"])
print(s2)

#결측치 채우기 #실수
print(s2.fillna(0))

#결측치 한 번에 채우면서 s2 변경 #정수
s2 = s.reindex(["메로나", "비비빅", "구구콘"], fill_value=0)
print(s2)

#연습
price = [42500, 42550, 41800, 42550, 42650]
date = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(price, date) #(data, index)
print(s)

#딕셔너리 이용
data = {
    "2019-05-31" : 42500,
    "2019-05-30" : 43550,
    "2019-05-29" : 41800,
    "2019-05-28" : 42550,
    "2019-05-27" : 42650
}
s = Series(data)
print(s)

print(s.index) #인덱스 값 분리해서 가져오기
print(s.index.dtype)
print(s.values) # valus 값 분리해서 가져오기 #ndarray로 가져옴
print(s.values.dtype)

"""3.4 시리즈 인덱싱: 인덱싱은 하나의 값에 접근하는 것
*   리스트는 인덱스로만 인덱싱 했지만 시리즈는 행 번호와 인덱스 사용 가능 (시리즈는 행 번호 자동 부여)
*  행 번호 인덱싱 : iloc 연산 = 리스트 인덱싱과 동일
*  인덱스 인덱싱: loc 연산

"""

# 행 번호 인덱싱
data = [1000, 2000, 3000]
s = Series(data=data)

print(s.iloc[0])
print(s.iloc[1])
print(s.iloc[2])
print(s.iloc[-1])

# 인덱스 인덱싱
print(s.loc[0])
print(s.loc[1])
print(s.loc[2])
#print(s.loc[-1]) -> 에러. -1이라는 인덱스가 시리즈에 없기 때문.

# 문자열 인덱스 인덱싱
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data, index)

print(s.iloc[0])
print(s.loc["메로나"])

#[]만 이용할 수도. 알맞는 데이터를 찾아서 반환함.
print(s['메로나'])
print(s[0])

#[]는 기본적으로 loc 호출. 그치만 문자열 -> iloc
s1 = Series([10, 20, 30])
s2 = Series([10, 20, 30], index=[1,2,3])
s3 = Series([10,20,30], index=['a','b','c'])
print(s1[0])
#print(s2[0])
print(s3[0])
# =>  헷갈리니까 이렇게 하지 말자.

#시리즈 인덱스도 []인덱싱 쓸 수도 있다. 숫자일 때만.
print(s3.index[0])
print(s3.index[-1])

"""3.5 시리즈 슬라이싱"""

data = [1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
s = Series(data, index)

#iloc이용 슬라이싱
print(s.iloc[0:2])

#loc 슬라이싱
print(s.loc['메로나':'구구콘']) #loc 슬라이싱은 [시작:끝(포함)]

#연속적이지 않은 값들 슬라이싱
indice = [0,2]
print(s.iloc[indice])
print(s.iloc[[0,2]]) #바깥 대괄호 -> 인덱싱, 안 대괄호 -> 리스트

indice = ['메로나', '하겐다즈']
print(s.loc[indice])
print(s.loc[['메로나', '하겐다즈']])

"""3.6 시리즈 수정/추가/삭제"""

data = [1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
s = Series(data, index)

#수정
s.loc['메로나'] = 500
print(s)

s.iloc[0] = 1000
print(s)

s['메로나'] = 500
print(s)

#추가
#시리즈에 인덱스에 해당하는 값이 있으면 수정되고, 없으면 추가된다.
s.loc['비비빅'] = 500
print(s)

#삭제
#drop-> 시리즈 인덱스만 사용 가능하다.
print(s.drop('메로나'))
#print(s.drop(0)) ->에러

s = s.drop('메로나')
print(s)

"""3.7 시리즈 연산
*  넘파이처럼 브로드캐스팅 적용됨.
*  같은 인덱스 갖는 데이터끼리 연산 수행.
"""

철수 = Series([10, 20,30], index=['NAVER','SKT','KT'])
영희 = Series([10,20,30], index=['SKT',"KT",'NAVER'])
가족 = 철수 + 영희
print(가족) #같은 인덱스끼리 연산

print(철수 * 10)

high = Series([42800, 42700, 42050, 42950, 43000])
low = Series([42150, 42150, 41300, 42150, 42350])
diff = high - low
print(diff) #자동맵핑된 정수 인덱스. 같은 인덱스끼리 연산

print(diff.max())

date = ['6/1', '6/2', '6/3', '6/4', '6/5']
high = Series([42800, 42700, 42050, 42950, 43000], index = date)
low = Series([42150, 42150, 41300, 42150, 42350],index = date)

# 변동폭 계산하기

diff = high - low
print(diff)

print(diff.max()) #최댓값을 반환
print(diff.min()) #최솟값을 반환

print(diff.idxmax()) #최댓값일 때 인덱스를 반환
print(diff.idxmin()) #최솟값일 때 인덱스를 반환


# 수익률 계산하기
profit = high / low
print(profit)

print(profit.cumprod()) #누적 수익률 = 모든 수익률 누적해서 곱함
print(profit.cumprod().iloc[-1]) #최종 누적 수익률만 프린트 하기

data = {
    "삼성전자" : "전기,전자",
    "LG전자" : "전기,전자",
    "현대차" : "운수장비",
    "NAVER" : "서비스업",
    "카카오" : "서비스업"
}
s = Series(data)

#unique
#중복 제거.values 중 유일한 값들만 ndarray로 반환
print(s.unique())

#value_counts
s.value_counts() #시리즈로 반환

"""3.8 시리즈와 Map"""

#문자-> 숫자로 바꾸기

s = Series(['1,234', '5,678', '9,876'])
#print(int(s))-> 콤마 때문에 에러

def remove_comma(x):
  print(x, 'in function')
  return x
result = s.map(remove_comma) #함수의 이름만 map 매서드로 연결
print(result)


def remove_comma(x):
  return int(x.replace(",", ""))
result = s.map(remove_comma)
print(result)

#수치형 데이터를 범주형 데이터로 구분
def is_greater_than_5000(x):
  if x > 5000:
    return "크다"
  else:
    return "작다"

s = Series([1234, 5678, 9876])
s = s.map(is_greater_than_5000)
print(s)

"""3.9 시리즈 필터링"""

data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = Series(data, index)
cond = s > 42000 # cond = condition
print(cond)
print(s[cond])

close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open = Series(open, index = index)
close = Series(close, index = index)

cond = close > open
print(cond)
print(close[cond])
print(open[cond])

print(close[close>open])

print(close.index[close > open]) #인덱스(날짜)만 출력하기
print(close[close > open].index) #방법2

#변동폭
diff = close - open
print(diff[ close > open])

"""3.10 정렬 및 순위"""

data = [3.1, 2.0, 10.1, 5.1]
index = ['000010', '000020', '000030', '000040']
s = Series(data, index=index)
print(s)

# 정렬 (오름차순)
s1 = s.sort_values()
print(s1)

#정렬 (내림차순)
s2 = s.sort_values(ascending = False)
print(s2)

# 순위 매기기
print(s.rank()) # PER이 제일 작은 000020 인덱스 항목의 순위가 1.0임.

# 순위 매기기 (큰 순위)
print(s.rank(ascending=False))