# -*- coding: utf-8 -*-
"""ch04_pasdas-dataframe01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DynSjUJtp_ZbZ9EU-xNIZ171gBdb_MZ
"""

!pip install pandas

"""4.1 데이터프레임 소개 및 생성


*   판다스 시리즈 -> 1차원
*   데이터 프레임 -> 2차원

"""

from pandas import DataFrame

# 방법1: 딕셔너리
data = {
    '종목코드' : ['037730', '036360', '005760'],
    '종목명' : ['3R', '3SOFT', 'ACTS'],
    '현재가' : [1510, 1790, 1185]
}

df = DataFrame(data)
print(df)

# 방법2: 리스트
data = [
    ['037730', '3R', 1510],
    ['036360', '3SOFT', 1790],
    ['005760', 'ACTS', 1185]
]
columns = ["종목코드", "종목명", "현재가"]

df = DataFrame(data=data, columns=columns)
print(df)

# 방법3: 리스트와 딕셔너리
data = [
    {"종목코드" : "037730", "종목명" : "3R", "현재가" : 1510},
    {"종목코드" : "036360", "종목명" : "3SOFT", "현재가" : 1790},
    {"종목코드" : "005760", "종목명" : "ACTS", "현재가" : 1185}
]

df = DataFrame(data=data)
print(df)


#각각의 시리즈는 동일한 인덱스를 갖는다

"""4.2 데이터프레임의 인덱스 (로우의 데이터를 구분하는 용도)"""

data = [
    ['037730', '3R', 1510, 7.36],
    ['036360', '3SOFT', 1790, 1.65],
    ['005760', 'ACTS', 1185, 1.28]
]
columns = ["종목코드", "종목명", "현재가", "등락률"]

df = DataFrame(data=data, columns=columns)
print(df)

# set_index 매서드
# 자동 생성된 0,1,2대신 종목코드 컬럼으로 인덱스 변경하기
df = df.set_index('종목코드')
print(df)

# 수정 반영
# df.set_index('종목코드', inplace=True)


# 인덱스를 별도 지정하는 방식
data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]

df = DataFrame(data=data, index=index, columns=columns)
df.index.name = "종목코드" # 인덱스 이름 설정하기
print(df)

"""4.3 컬럼 인덱싱"""

print(df['현재가']) # 기본적으로 []-> 컬럼 단위 인덱싱
print(df.현재가) # 이렇게 할 수도

# 여러 개의 칼럼 슬라이싱하기
리스트 = ['현재가', '등락률']
print(df[리스트])

# 당연히 이렇게도 됨
print(df[['현재가', '등락률']])

"""

*   한 개의 열만 인덱싱 -> 시리즈
*   리스트로 슬라이싱 -> 데이터프레임

"""

df[["현재가"]]

df['현재가']

print(type(df[["현재가"]]))
print(type(df["현재가"]))

"""4.4 로우 인덱싱"""

# loc: 인덱스 기준으로 로우 데이터 추출
print(df.loc["037730"])

# iloc: 행 번호 기준으로 로우 데이터 추출
print(df.iloc[0])
print(df.iloc[-1])

# 불연속적인 값들 가져오기
print(df.loc[["037730", "036360"]])
print(df.iloc[[0,1]])

"""4.5 특정 값 가져오기"""

# 시리즈로 리턴됨.
print(df.iloc[0])
print(df.loc['037730'])

# 행 번호로 행 선택 후 시리즈 인덱싱
print(df.iloc[0].iloc[1])      # 시리즈 행 번호
print(df.iloc[0].loc['현재가'])  # 시리즈 인덱스
print(df.iloc[0]['현재가'])      # 시리즈 인덱스

# 인덱스로 행 선택 후 시리즈 인덱싱
print(df.loc["037730"].iloc[1])
print(df.loc["037730"].loc["현재가"])
print(df.loc["037730"]["현재가"])

# 한 번에 접근
print(df.loc["037730", "현재가"])
print(df.iloc[0,1])

# 이런식으로 한 번에 접근도 가능하지만 되도록이면 위의 df.loc[행,열]을 쓰자.
print(df['현재가'].iloc[0])
print(df['현재가'].loc["037730"])
print(df['현재가']["037730"])

"""4.6 특정 범위 가져오기"""

# 방법1
print(df.loc[["037730", "036360"]])
print(df.iloc[[0,1]])

# 방법2
df = df.loc[["037730", "036360"]]
df = df[["종목명", "현재가"]]
print(df)

# 방법3
print(df.loc[["037730", "036360"], ['종목명', '현재가']])
print(df.iloc[[0,1],[0,1]])

"""4.7 데이터프레임 필터링"""

data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]

df = DataFrame(data=data, index=index, columns=columns)
cond = df['현재가'] >= 1400
print(df.loc[cond]) # 데이터 프레임 슬라이싱의 결과 = 데이터프레임

#칼럼의 이름으로 인덱실
print(df.loc[cond]['현재가'])
print(df.loc[cond,'현재가']) # 위 라인보다 이 방법이 더 빠르다.

# 복잡한 조건 -> 논리연산자
cond = (df['현재가'] >= 1400) & (df['현재가'] < 1700) # & 쓸 때는 무조건 괄호 구분
print(df.loc[cond])
print(df.loc[~cond]) # not 연산자

"""4.8 칼럼 추가하기"""

from pandas import Series

data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]
df = DataFrame(data=data, index=index, columns=columns)

s = Series(data=[1600,1600,1600], index=df.index)
df['목표가'] = s
print(df)

df['괴리율'] = (df['목표가']-df['현재가'])/df['현재가']
print(df)

"""4.9 로우 추가하기"""

data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]
df = DataFrame(data=data, index=index, columns=columns)

s = Series(data=["LG전자", 6000, 3.84],index=df.columns)
df.loc["066570"] = s
print(df)

# 간단히 표현하기.

data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]
df = DataFrame(data=data, index=index, columns=columns)

df.loc["066570"] = ["LG전자", 6000, 3.84]
print(df)

"""4.10 칼럼/로우 삭제하기"""

# 칼럼 삭제
data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]
df = DataFrame(data=data, index=index, columns=columns)

df_new = df.drop("현재가", axis=1)
print(df)
print(df_new)

# 로우 삭제
data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]
df = DataFrame(data=data, index=index, columns=columns)

df_new = df.drop("037730", axis = 0)
print(df)
print(df_new)

df.drop("037730", axis=0, inplace= True) # 원본 데이터 프레임 변경
print(df)

# 한 번에 여러개의 로우, 칼럼 삭제 -> 리스트 형태
data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]
df = DataFrame(data=data, index=index, columns=columns)

df.drop(["037730", "005760"], axis=0, inplace= True)
print(df)

"""4.11 칼럼 레이블 변경"""

data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]
df = DataFrame(data=data, index=index, columns=columns)

print(df.columns)
print(df.index)

df.columns = ['name','close','fluctuation'] # 칼럼 이름 변경
df.index.name='code' # 인덱스 name 변경
print(df)

# rename 매서드
# {"변경 전 이름" : "변경 후 이름"}
# inplace = Ture는 원본 데이터 수정하는 옵션

data = [
    ['3R', 1510, 7.36],
    ['3SOFT', 1790, 1.65],
    ['ACTS', 1185, 1.28]
]
columns = ["종목명", "현재가", "등락률"]
index = ["037730", "036360", "005760"]
df = DataFrame(data=data, index=index, columns=columns)

df.rename(columns={'종목명':'name'}, inplace=True)
print(df)

"""4.12 데이터 타입 변경"""

from pandas import DataFrame

data = [
    ['1,000', '1,100', '1,510'],
    ['1,410', '1,420', '1,790'],
    ['850', '900', '1,185']
]
columns = ["03/02", "03/03", "03/04"]
df = DataFrame(data=data, index=index, columns=columns)

print(df) # 현재 현재가가 문자열로 저장되어 있음.

# 정수로 변경하기
def remove_comma(x):
  return int(x.replace(',',''))

df['03/02']=df['03/02'].map(remove_comma)
df['03/03']=df['03/03'].map(remove_comma)
df['03/04']=df['03/04'].map(remove_comma)
print(df)


# applymap 메서드
data = [
    ['1,000', '1,100', '1,510'],
    ['1,410', '1,420', '1,790'],
    ['850', '900', '1,185']
]
columns = ["03/02", "03/03", "03/04"]
df = DataFrame(data=data, index=index, columns=columns)

df=df.applymap(remove_comma)
print(df)
print(df.dtypes)

# astype 메서드로 데이터 타입 변경하기
import numpy as np
from pandas import DataFrame

data = [
    ['1,000', '1,100', '1,510'],
    ['1,410', '1,420', '1,790'],
    ['850', '900', '1,185']
]
columns = ["03/02", "03/03", "03/04"]
df = DataFrame(data=data, index=index, columns=columns)

df=df.applymap(remove_comma)
df=df.astype({"03/02":np.int64,"03/03":np.int64,"03/04":np.int64})
print(df.dtypes)

"""4.13 컬럼의 문자열 다루기"""

from pandas import DataFrame
import numpy as np


data = [
    {"cd":"A060310","nm":"3S","close":"2,920"},
    {"cd":"A095570", "nm":"AJ네트웍스","close":"6,250"},
    {"cd":"A006840","nm":"AK홀딩스","close":"29,700"},
    {"cd":"A054620","nm":"APS홀딩스","close":"19,400"}
]
df=DataFrame(data=data)
print(df)

df['cd']=df['cd'].str[1:] #'cd'칼럼의 종목코드에서 A를 제거한 나머지 6자리 사용. str->시리즈에 저장된 문자열 칼럼에서만.
print(df)

df['close']=df['close'].str.replace(',','').astype(np.int64) # 콤마를 공백으로 제거하기
print(df)

