# -*- coding: utf-8 -*-
"""ch05_pandas-dataframe02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DMvK2ZqZRUoaK-7BFVsvTpZqsz2TmeYp

5.1 Query
"""

from pandas import DataFrame

data = [
    {"cd":"A060310","nm":"3S","open":2920, "close":2920},
    {"cd":"A095570", "nm":"AJ네트웍스","open":1920, "close":6250},
    {"cd":"A006840","nm":"AK홀딩스","open":2020, "close":29700},
    {"cd":"A054620","nm":"APS홀딩스","open":3120, "close":19400}
]
df=DataFrame(data=data)
df=df.set_index('cd')
print(df)

# 불린형 데이터가 담긴 조건 시리즈로 슬라이싱
cond = df['open'] >= 2000
print(df[cond])

# query 매서드로 필터링
# nm이라는 칼럼에서 3S라는 값을 갖는 데이터를 필터링
print(df.query("nm=='3S'")) # 큰 따옴표로 전체 쿼리, 작은 따옴표 문자열
print(df.query('nm=="3S"')) # 반대로 할수도

# 쿼리 필터링 예시2
print(df.query("open>close"))

# 예시 3
# not in -> 포함되지 않는 종목 선택
print(df.query("nm in ['3S','AK홀딩스']"))

# 예시 4
# 인덱스 기준으로 조회하기
df.query("cd == 'A060310'")

# 예시 5
# @ 키워드-> 파이썬 변수 사용할 수 있다.
name = "AJ네트웍스"
df.query('nm==@name')

"""5.2 Filter"""

from pandas import DataFrame

data = [
    [1416,1416,2994,1755],
    [6.42,17.63,21.09,13.93],
    [1.10,1.49,2.06,1.88]
]
columns=["2018/12","2019/12","2020/12","2021/12(E)"] # 2021은 추정치라는 의미로 (E) 표시
index=["DPS","PER","PBR"]

df = DataFrame(data=data, index=index, columns=columns)
print(df)

# filter 매서드의 items 파라미터로 선택할 칼럼의 이름 지정하기
# filter -> dataframe으로 반환
df.filter(items=['2018/12'])

# 인덱스 필터링하기
# axis 입력 안하면 기본1로 됨 (칼럼 탐색)
df.filter(items=["PER"],axis=0)

# regex 파라미터
df.filter(regex="2020")

df.filter(regex="^2020") # 2020으로 시작하는 문자열 패턴만 선택

df.filter(regex="R$", axis = 0) # 인덱스에서 R로 끝나는 패턴만 선택

# \d -> 숫자를 의미한다
# {} -> 출현횟수를 지정한다.
df.filter(regex="\d{4}") # 연속해서 숫자 네 개가 발생하는 문자열만 탐색

df.filter(regex="\d{4}/\d{2}$") # 숫자 네 개와 /, 숫자 두 개로 구성된 칼럼을 선택. (E) 제외

"""5.3 정렬 및 순위"""

from pandas import DataFrame

data = [
    ["037730","3R",1510],
    ["036360","3SOFT",1790],
    ["005670","ACTS",1185]
]
columns = ["종목코드","종목명","현재가"]
df = DataFrame(data=data, columns=columns)
df.set_index("종목코드",inplace=True)

# 현재가 컬럼을 기준으로 정렬
df2_1 = df.sort_values("현재가")
print(df2_1)

# 파라미터 이름을 지정해서 정렬
df2_2 = df.sort_values(by="현재가")
print(df2_2)

# 내림차순-> ascending 파라미터 = False (기본은 True)
df2 = df.sort_values(by="현재가",ascending=False)
print(df2)

# 순위 매기기 (낮은 종목부터)
df['순위']=df['현재가'].rank()
print(df)

# 순위별로 정렬하기
# sort_values 메서드
df.sort_values(by="순위", inplace=True)
print(df)

"""5.4 인덱스 연산"""

import pandas as pd

idx1 = pd.Index([1,2,3])
idx2 = pd.Index([2,3,4])
print(type(idx1))

# union 메서드
# 현재의 인덱스와 입력된 인덱스를 합쳐 중복 제거. "합집합"
idx1.union(idx2)

# intersection 메서드
# "교집합"
idx1.intersection(idx2)

# difference 메서드
# "차집합" idx1 - idx2
idx1.difference(idx2)

"""5.5 GroupBy

① 무엇으로 묶을 것인가?

groupby("테마")

↓

② 어떤 컬럼을 계산할 것인가?

["PER"]

↓

③ 어떤 계산을 할 것인가?

.mean()
.max()
.min()
.sum()
.count()
.agg(...)
"""

from pandas import DataFrame

data = [
    ["2차전지(생산)","SK이노베이션", 10.19,1.29],
    ["해운","팬오션",21.23,0.95],
    ["시스템반도체","티엘아이",35.97,1.12],
    ["해운","HMM",21.52,3.20],
    ["시스템반도체","아이에이",37.32,3.55],
    ["2차전지(생산)","LG화학",83.06,3.75]
]

columns=["테마","종목명","PER","PBR"]
df=DataFrame(data=data,columns=columns)

# 테마별로 종목을 분류하기
df1=df[df['테마']=="2차전지(생산)"]
print(df1)

df2=df[df['테마']=="해운"]
print(df2)

df3=df[df['테마']=="시스템반도체"]
print(df3)

# 테마별로 그룹화한 데이터프레임에서 PER 컬럼의 평균값 계산하기
# 데이터 프레임의 컬럼은 시리즈 객체.
# 시리즈 객체의 mean 매서드 이용
mean1 = df1['PER'].mean()
mean2 = df2['PER'].mean()
mean3 = df3['PER'].mean()

# PER 평균을 시리즈로 저장하기
data = [mean1,mean2,mean3]
index = ["2차전지(생산)","해운","시스템반도체"]
s = pd.Series(data=data,index=index)
print(s)

# 위의 과정: 테마별로 split -> 계산 apply -> 결과를 combine
# groupby 메서드로 간소화할 수 있다.
df.groupby("테마")["PER"].mean()

# 2차 전지 테마의 데이터만 선택하기
gb = df.groupby("테마")
temp = gb.get_group("2차전지(생산)")
print(temp)

# 종목명을 제외하고 PER과 PBR만 선택하기
temp = df[["테마","PER","PBR"]].groupby("테마").get_group("2차전지(생산)")
print(temp)

# DataFrameGoupBy 객체를 슬라이싱하기
temp = df.groupby("테마")[["PER","PBR"]].get_group("2차전지(생산)")
print(temp)

# 여러 개의 컬럼 + 집계 기능
# groupby(그룹화)-> PER, PBR에 mean 메서드 -> 데이터프레임 반환
df.groupby("테마")[["PER","PBR"]].mean()

# 데이터 프레임을 그룹화한 후 특정 칼럼마다 다른 함수를 적용하기
df.groupby("테마").agg({"PER":max,"PBR":min}) # aggregate = 모으다, 집계하다, 종합하다

# 하나의 컬럼에 여러 연산을 지정하기
import numpy as np
df.groupby("테마").agg({"PER":[min,max],"PBR":[np.std,np.var]})

"""5.6 좌/우로 붙이기"""

from pandas import DataFrame
import pandas as pd

# 첫 번째 데이터프레임
data = {
    '종가':[113000,111500],
    '거래량':[555850,282163]
}
index=['2019-06-21','2019-06-20']
df1=DataFrame(data=data,index=index)
print(df1)

# 두 번때 데이터프레임
data = {
    '시가': [ 112500, 110000],
    '고가': [115000,112000],
    '저가': [115000,109000]
}
index=['2019-06-21','2019-06-20']
df2=DataFrame(data=data, index=index)
print(df2)

# concat 함수 -> 기본적으로 같은 컬럼 레이블을 갖는 데이터프레임을 위/아래로 연결
# axis = 1 -> 리스트로 전달된 데이터 프레임을 좌/우로 연결
# 인덱스를 기준으로 데이터를 연결한다.
df=pd.concat([df1,df2], axis=1)
print(df)

# 컬럼의 순서 변경하기
정렬순서 = ['시가','고가','저가','종가','거래량']
df=df[정렬순서]
print(df)

# 인덱스가 다른 데이터 프레임의 경우

data = {
    '종가':[113000,111500],
    '거래량':[555850,282163]
}
index=['2019-06-21','2019-06-20']
df1=DataFrame(data=data,index=index)
print(df1)

data = {
    '시가':[112500,110000],
    '고가':[115000,112000],
    '저가':[111500,109000]
}
index=["2019-06-20","2019-06-19"]
df2=DataFrame(data=data,index=index)
print(df2)

# 결측값 NaN으로 표기된다.
df = pd.concat([df1,df2], axis=1)
print(df)

# join 파라미터
# outer 옵션 -> 합집합 (기본값)
# inner 옵션 -> 교집합
df = pd.concat([df1,df2], axis=1, join='inner')
print(df)

"""5.7 위/아래로 붙이기"""

from pandas import DataFrame
import pandas as pd

# 첫 번째 데이터프레임
data = {
    '종가':[113000,111500],
    '거래량':[555850,282163]
}
index=['2019-06-21','2019-06-20']
df1=DataFrame(data=data,index=index)
print(df1)

# 두 번때 데이터프레임
data = {
    '종가' : [110000, 483689],
    '거래량' : [109000, 791946]
}
index=['2019-06-19','2019-06-18']
df2 = DataFrame(data=data, index=index)
print(df2)

# axis=0으로 concat 함수 호출
# concatenate = 이어 붙이다, 연결하다
# 기본은 join = 'outer'
df = pd.concat([df1,df2])
print(df)

"""5.8 Merge = 병합"""

# 첫 번째 데이터프레임
data = [
    ["전기전가","005930","삼성전자", 74400],
    ["화학","051910","LG화학",896000],
    ["전지전자","000660","SK하이닉스",101500]
]
columns= ['업종','종목코드','종목명','현재가']
df1 = DataFrame(data=data, columns=columns)
print(df1)

# 두 번째 데이터프레임
data = [
    ["은행", 2.92],
    ["보험", 0.37],
    ["화학", 0.06],
    ["전기전자", -2.43]
]
columns = ['업종','등락률']
df2 =DataFrame(data=data,columns=columns)
print(df2)

# on 파라미터 -> 데이터 프레임을 합칠 기준값(컬럼명)
df = pd.merge(left=df1, right=df2, on='업종')
print(df)

# 첫 번째 데이터프레임
data = [
    ["전기전가","005930","삼성전자", 74400],
    ["화학","051910","LG화학",896000],
    ["서비스업","035720","카카오",121500]
]
columns= ['업종','종목코드','종목명','현재가']
df1 = DataFrame(data=data, columns=columns)
print(df1)

# 두 번째 데이터프레임
data = [
    ["은행", 2.92],
    ["보험", 0.37],
    ["화학", 0.06],
    ["전기전자", -2.43]
]
columns = ['업종','등락률']
df2 =DataFrame(data=data,columns=columns)
print(df2)

# how 파라미터로 병합하기
# inner -> 교집합, outer -> 합집합
df = pd.merge(left=df1, right=df2, how='left', on='업종') #how='left'-> df1 기준으로 병합
print(df)

# 두 데이터프레임의 컬럼이 다를 때
# 첫 번째 데이터프레임
data = [
    ["전기전가","005930","삼성전자", 74400],
    ["화학","051910","LG화학",896000],
    ["서비스업","035720","카카오",121500]
]
columns= ['업종','종목코드','종목명','현재가']
df1 = DataFrame(data=data, columns=columns)
print(df1)

# 두 번째 데이터프레임
data = [
    ["은행", 2.92],
    ["보험", 0.37],
    ["화학", 0.06],
    ["전기전자", -2.43]
]
columns = ['항목','등락률']
df2 =DataFrame(data=data,columns=columns)
print(df2)

# 합칠 기준이 되는 각 칼럼의 이름을 모두 입력한다.
df = pd.merge(left=df1, right=df2, left_on='업종', right_on='항목')
print(df)

"""5.9 Join"""

from pandas import DataFrame
import pandas as pd

# 첫 번째 데이트프레임
data = [
    ["전기전자","005930","삼성전자",74400],
    ["화학","051910","LG화학",896000],
    ["서비스업","035720","카카오",121500]
]
columns=["업종","종목코드","종목명","현재가"]
df1 = DataFrame(data=data, columns=columns)
df1 = df1.set_index("업종")
print(df1)

# 두 번째 데이터프레임
data = [
    ["은행",2.92],
    ["보험",0.37],
    ["화학",0.06],
    ["전기전자",-2.43]
]
columns=["항목","등락률"]
df2 = DataFrame(data=data,columns=columns)
df2=df2.set_index("항목")
print(df2)

# join 메서드 other 파라미터로 병합할 데이터프레임 전달
df1.join(other=df2)
# how 파라미터로 left/right/outer/inner 지정 가능. 기본:left

# 시가총액으로 대형주와 중/소형주로 구분하기
data = [
    ["2017","삼성",500],
    ["2017","LG",300],
    ["2017","SK하이닉스",200],
    ["2018","삼성",600],
    ["2018","LG",400],
    ["2018","SK하이닉스",300]
]
columns=["연도","회사","시가총액"]
df=DataFrame(data=data,columns=columns)
print(df)

df_mean = df.groupby("연도")["시가총액"].mean().to_frame() # 시가총액의 평균만 반환(시리즈) -> to_frame 메서드를 사용해서 데이터프레임을 얻는다.
df_mean.columns = ['시가총액평균']
print(df_mean)

df = DataFrame(data=data, columns=columns)

df = df.join(df_mean, on='연도')
print(df)

import numpy as np

df['규모']=np.where(df['시가총액']>=df['시가총액평균'], "대형주", "중/소형주")
print(df)

"""5.10 Multi-Index"""

from pandas import DataFrame
import pandas as pd

data = [
    ['영업이익','컨센서스',1000,1200],
    ['영업이익','잠정치',900,1400],
    ['당기순이익','컨센서스',800,900],
    ['당기순이익','잠정치',700,800],
]
df = DataFrame(data=data)
df = df.set_index([0,1]) # level 0 인덱스 - level 1 인덱스
print(df)

df.index.names = ["재무연월",""] # 인덱스 이름 변경하기. level1 인덱스는 공백으로.
df.columns = ["2020/06","2020/09"]
print(df)

print(df.loc['영업이익']) # 영업이익을 인덱싱한 데이터프레임
print(df.loc[('영업이익','컨센서스')]) #df.loc['영업이익']['컨센서스'] 방식은 두 번의 인덱싱이 적용되어 느리다. level 0부터 level N까지 튜플로 정의하기.

print(df.iloc[0]) # iloc-> 인덱스 레벨과 무관하게 하나의 로우 선택. 칼럼이름을 인덱스로 갖는 시리즈로 반환
print(df.iloc[0,0])
print(df.loc[('영업이익','컨센서스'),'2020/06']) # 멀티 인덱스의 값을 선택하기 위해 튜플 사용

# slice(시작, 끝, 증감폭)
a = [1,2,3,4,5]
print(a[0:5:2])
print(a[slice(0,5,2)])

# slice 예시2
a = [1,2,3,4,5]
b = [3,4,5,6,7]

s = slice(0,5,2)
print(a[s])
print(b[s])

# slice(None)
a = [1,2,3,4,5]

print(a[:])
print(a[slice(None)])
print(a[::])
print(a[slice(None,None)])

# level 0 인덱스 전체의 level 1의 컨센서스만 선택하기
# print(df.loc[(:,'컨센서스'),:]) -> 에러
print(df.loc[(slice(None),'컨센서스'),:])

# IndexSlice -> 인덱싱 기호와 함께 ['level0', 'level1', 'level2'] 형태로 인덱스를 차례로 지정한다.
idx = pd.IndexSlice # 짧은 이름으로 쓰기 위해서.
print(df.loc[idx[ : , '컨센서스'], : ]) # level0-> 모든값, level1->컨센서스

"""5.11 Multi-Coulumn"""

from pandas import DataFrame

data = [
    [1000, 900, 800, 700],
    [1200, 1400, 900, 800],
]

columns = [
    ['영업이익', '영업이익', '당기순이익', '당기순이익'], # level 0
    ['컨센서스', '잠정치', '컨센서스', '잠정치'], # level 1
]

df = DataFrame(data=data, index=["2020/06","2020/09"],columns=columns)
print(df)

# MultiIndex의 from_product 함수-> 입력된 리스트로 데이터의 조합을 만든다
import pandas as pd

level_0 = ['영업이익', '당기순이익']
level_1 = ['컨센서스', '잠정치']

idx = pd.MultiIndex.from_product([level_0,level_1])

print(idx)
print(idx.get_level_values(0))

# from_product 결과를 데이터 프레임으로 연결
columns = pd.MultiIndex.from_product([level_0,level_1])
df = DataFrame(data=data, index=["2020/06","2020/09"],columns=columns)
print(df)

# 멀티 컬럼 데이터에서 영업이익 컬럼 인덱싱
print(df['영업이익']) # 컬럼 인덱싱 -> 대괄호 [] =-> 데이터 프레임

print(df[('영업이익','컨센서스')]) # 튜플로 여러번 인덱싱. level을 계층적으로 표현.

# 예시들
print(df['영업이익']) # 컬럼 선택 -> 데이터프레임 반환
print(df.loc['2020/06','영업이익']) # 시리즈로 출력
print(df.loc['2020/06',('영업이익', '컨센서스')]) # 정수로 출력
print(df.loc['2020/06',(slice(None), '컨센서스')]) # 영업이익의 컨센서스, 당기순이익의 컨센서스가 시리즈로 출력

# transpose 메서드 또는 T 속성 -> 데이터의 x축과 y축이 변경된다.
print(df.transpose())
print(df.T)

"""5.12 Stack / Unstack


*   stack: column -> index
*   unstack: index-> column


"""

from pandas import DataFrame
import pandas as pd

data = [
    [1000, 900, 800, 700],
    [1200, 1400, 900, 800],
]

level_0 = ['영업이익', '당기순이익']
level_1 = ['컨센서스', '잠정치']
columns = pd.MultiIndex.from_product([level_0,level_1])

df = DataFrame(data=data, index=['2020/06','2020/09'], columns=columns)
print(df.stack()) # 가장 높은 레벨의 컬럼이 인덱스로 변경
print(df.stack(level=0))

print(df.stack().stack()) # 3차원으로 만들기

print(df.stack().unstack()) # 되돌리기

from pandas import DataFrame
import pandas as pd

data = [
    [1000, 1100, 900, 1200, 1300],
    [800, 2000, 1700, 1500, 1800]
]
index = ['자본금', '부채']
columns = ['2020/03', '2020/06', '2020/09', '2021/03','2021/06']
df = DataFrame(data, index, columns)
print(df) # 연도와 월이 섞여 있어서 불편. 이제 이걸 분리해보자.

df_stacked = df.stack().reset_index() # level_0, level_1 자동부여
print(df_stacked)

temp = df_stacked['level_1'].str.split('/') # 시리즈 변환 (각각의 값이 리스트)
print(temp)

df_split = DataFrame(list(df_stacked['level_1'].str.split('/'))) # 반환된 시이즈 -> 리스트 변환 -> 데이터프레임으로 변환
print(df_split)

df_merged = pd.concat([df_stacked, df_split], axis=1)
df_merged.columns = ['계정', '년월', '금액', '연도' ,'월']
print(df_merged)

df_group = df_merged.groupby(['계정', '연도']).sum()
print(df_group)

df_unstack = df_group.unstack()
result = df_unstack['금액']
result.columns.name = '' # 컬럼 이름 제거
result.index.name = '' # 인덱스 이름 제거
print(result)

"""5.13 Pivot: 필요한 데이터를 추출해서 데이터를 재구성하는 기능"""

from pandas import DataFrame
import pandas as pd

data = [
    ['2021-08-12', '삼성전자', 77000],
    ['2021-08-13', '삼성전자', 74400],
    ['2021-08-12', 'LG전자', 153000],
    ['2021-08-13', 'LG전자', 150500],
    ['2021-08-12', 'SK하이닉스', 100500],
    ['2021-08-13', 'SK하이닉스', 101500],
]
columns = ['날짜', '종목명', '종가']
df = DataFrame(data=data, columns=columns)
print(df)

df1 = pd.pivot(data=df, index='날짜', columns='종목명', values='종가') # pivot의 파라미터 data, index, columns, values
print(df1)

df.groupby(['날짜','종목명']).mean().unstack()
df2=pd.pivot(data=df, index='종목명', columns='날짜', values = '종가')
print(df2) # 날짜가 더 보기 좋아졌음 !

"""5.14 Melt: 칼럼의 수가 많아서 넓은 와이드 포맷의 데이터프레임을 세로로 긴 롱 포맷의 데이터프레임으로 재구조화"""

from pandas import DataFrame

data = [
    ['005930', '삼성전가', 75800, 76000, 74100, 74400],
    ['035720','카카오', 147500, 147500, 144500, 146000],
    ['000660','SK하이닉스', 99600, 101500, 98900, 101500]
]

columns = ['종목코드', '종목명', '시가', '고가', '저가', '종가']
df = DataFrame(data=data, columns=columns)
print(df)

df.melt(id_vars=['종목코드', '종목명']) # 종목코드와 종목명을 제외하고 나머지 데이터를 melt

df.melt(value_vars=['시가','종가']) # 리스트로 칼럼 이름 전달. 지정한 시가, 종가 칼럼에 대해서만 melt 적용

"""5.15 파일 저장하기"""

from pandas import DataFrame
data ={
    "종목명" :["3R","3SOFT","ACTS"],
    "현재가" : [1510, 1790, 1185],
    "등락률":[7.36, 1.65, 1.28],
}
df = DataFrame(data, index=["037730","036360","005760"])

df.to_csv("data.csv")
# 엑셀은 to_excel()
# sheet_name = ""

"""5.16 파일 불러오기"""

import pandas as pd


# df = pd.read_excel("파일명.xlsx")
# df = pd.read_csv("파일명.csv")