# -*- coding: utf-8 -*-
"""ch06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lu5KhY1pDw_Ay4BRxldz03proOvY8gfW

6.1 Timestamp
"""

import pandas as pd

ts = pd.to_datetime("2021-01-2")
print(type(ts))
print(ts) # 문자열이 날짜를 표현하는 Timestamp 객체로 변환되었으며 시간/분/초를 입력하지 않아서 0시 0분 0초로 표현됨.

ts = pd.to_datetime("2021-01-02 09:00:00")
print(ts)

ts = pd.to_datetime("20210102 090000")
print(ts)

print(pd.to_datetime("06/07/20")) # 영국식 표기법 -> 원하지 않은 결과. -> %y, %m, %d 지정해주기
print(pd.to_datetime("06/07/20", format="%d/%m/%y"))

ts = pd.to_datetime("2021-08-14")
print(ts.year)
print(ts.month)
print(ts.day)
print(ts.hour)
print(ts.minute)
print(ts.second)
print(ts.weekday()) # weekday 매서드 -> 요일정보를 숫자로 반환. 월요일이 0.

print(ts.strftime("%y-%m-%d")) #strftime 메서드 -> timestamp를 다시 문자열 타입으로 변경
print(ts.strftime("%Y-%m-%d")) # 대문자 Y는 4자리 연도.

diff = pd.Timedelta(days= 100, hours =2, minutes = 30, seconds = 30) # Timedelta 객체 -> Timestamp 객체와 연산
print(diff)
print(ts + diff)

candidates = ['2021-01-01','2021-01-02','2021-01-03']
idx = pd.to_datetime(candidates) # to_datetime 함수 -> 리스트에 저장된 모든 문자열을 Timestamp로 변경
print(idx) # 변수 idx에는 DatetimeIndex라는 자료구조. 날짜에 특화.

# 리스트와 비슷한 순서가 있는 자료구조. 정수를 사용한 인덱싱과 슬라이싱 가능
print(idx[0])
print(idx[0:2])

print(idx.year)
print(idx.month)
print(idx.day)

day = 1628899200 / 60 / 60 / 24
year = day / 355
print(year)

dt = pd.to_datetime(1628899200, unit= 's') # 에포크 시간 -> 타임스탬프 객체로 변환. 입력하는 단위는 second
print(dt)

data = [
    {'시가':100,'고가':110,'저가':90,'종가':105},
    {'시가':100,'고가':112,'저가':80,'종가':95},
    {'시가':99,'고가':115,'저가':70,'종가':85},
    {'시가':70,'고가':80,'저가':60,'종가':75},
]
df = pd.DataFrame(data, index=['20200615','20200616','20200717','20200718'])
print(df)

# print(df.loc['202006']) 2020년 6월 데이터만 확인하고 싶다면? 이렇게는 안됨.

# 방법1: 조건 슬라이싱
cond = df.index.str[:6] == '202006'
print(df.loc[cond])

# 방법2: 타임스탬프 타입으로 변경 -> 슬라이싱
df.index = pd.to_datetime(df.index)
print(df)
print(df.loc['2020-06']) # 대시 넣어줘야함!

# 데이터 연도 한 번에 불러오기
df['date'] = df.index
print(df['date'].dt.year)

"""6.2 시계열 데이터의 활용"""

import pandas as pd

df = pd.read_csv("data_1724_20260718.csv", encoding="euc-kr")
df.head(3)

df.index=pd.to_datetime(df.index) # 문자열->타임스탬프
df=df.sort_index() # sort_index 메서드: 날짜 정렬

df = pd.read_csv("data_1724_20260718.csv", encoding="euc-kr", parse_dates=['일자']) # parse_dates 파라미터: 날짜 컬럼을 DatetimeIndex로 읽을 수 있음.
df=df.sort_values('일자')

print(df['일자'].dtype)
print(type(df['일자'].iloc[0]))

df['일자'].dt.quarter # dt 속성 + year, month, day, hour, minute, second, quarter. 시리즈로 반환

df=df[['일자','시가','저가','고가','종가']].copy() # 원본과 완전히 분리된 새로운 DataFrame을 만들어 이후의 수정이 안전하게 이루어지도록 한다.
df['year']=df['일자'].dt.year # 연도 분리
df['month']=df['일자'].dt.month # 월 분리
df.head()

gb=df.groupby(['year','month']) # year과 Month의 이차원 인덱스로 데이터 집계
gb.get_group((2026,7)).head() # get_group: 특정 데이터 확인하기

how = {
    '시가':'first',
    '저가':'min',
    '고가':'max',
    '종가':'last',
}
gb.agg(how)

# Grouper 클래스로 더 간단한 코드를 쓸수 있다.
df.groupby(pd.Grouper(key='일자',freq='m')).agg(how) # freq='m' -> 월별로 데이터를 분류하라
# freq 파라미터에서는 3m, w, d 등 쓸 수 있다.

"""6.3 컬럼 시프트"""

import pandas as pd
df=pd.read_csv("data_1724_20260718.csv", encoding="euc-kr", index_col=0)
df.index=pd.to_datetime(df.index)
df=df.sort_index()

df['거래량'].shift(1) # shift 메서드: 지정한 수만큼 데이터 이동. 음수로 이동폭을 지정할수도.
# NaN : Not a number

df['전일거래량']=df['거래량'].shift(1)
df[['거래량','전일거래량']]

df['전일거래량']=df['거래량'].shift(1)
cond=df['거래량']>df['전일거래량']
print(df[cond])

print('상승일:',len(df[cond]))
print('영업일:',len(df))

df['거래량'].diff() # diff 메서드
cond = df['거래량'].diff()>0
len(df[cond]) # 거래량 증가 유무 판단하기

# 간단한 절대 모멘텀 투자 전략
# 과거 6일 전의 종가 대비 당일 종가가 3% 높다면 강한 상승-> 매수
yeild = df['종가']/df['종가'].shift(6) # 당일 종가와 6일전 종가를 나눠서 상승률 계산
cond = yeild >=1.03 # 상승률이 3% 이상인지 비교
print(len(df[cond])) # 매매에 참여할 수 있었던 횟수 출력

# 모멘텀 조건을 충족한 다음 날 시가에 사서 종가에 팔았을 경우의 수익률 계산하기
cond.shift(1)
cond_modified=cond.shift(1).fillna(False) # NaN을 False로 치환
s=df.loc[cond_modified, '종가']/df.loc[cond_modified,'시가']
print(s.cumprod().iloc[-1])

"""6.4 이동평균"""

# 3일 이동평균 계산해보기
import pandas as pd

df=pd.read_csv("data_1724_20260718.csv", encoding="euc-kr", index_col=0)
df.index=pd.to_datetime(df.index)
df=df.sort_index()[['종가']]

df['종가D-1']=df['종가'].shift(1)
df['종가D-2']=df['종가'].shift(2)
df['ma3']=(df['종가']+df['종가D-1']+df['종가D-2'])/3
df.head()

# rolling 메서드: 파라미터로 몇 개의 데이터를 그룹화할지 지정
df['rolling3']=df['종가'].rolling(3).mean()
df.head()

# 시가가 5일 이평선을 돌파한다 = 상승 추세
# 상승 추세일 때의 투자 기회 횟수 구하기
df=pd.read_csv("data_1724_20260718.csv", encoding="euc-kr", index_col=0)
df.index=pd.to_datetime(df.index)

df['ma5']=df['종가'].rolling(5).mean().shift(1)
cond=df['ma5']<df['시가']
print('상승일:',len(df[cond]))
print('영업일:',len(df))

# 지수이동평균
from pandas import Series
data =[84200, 84900, 83200, 82100, 82600]
index = ['2021-02-15','2021-02-16','2021-02-17','2021-02-18','2021-02-19']
s=Series(data,index)
s.ewm(span=3,adjust=False).mean() # rolling 대신 시리즈의 ewm 메서드 이용
# span 파라미터 : 이동평균 탭 수
# adjust = True: 가중치를 내부적으로 보정한다.

"""6.5 데이터 샘플링"""

import pandas as pd

df=pd.read_csv("data_1724_20260718.csv", encoding="euc-kr", index_col=0)
df.index=pd.to_datetime(df.index)
df=df.sort_index()[['시가','저가','고가','종가','거래량']]
df.head()

df.resample('M').first() # resample 메서드: 입력된 파라미터에 따라 데이터를 샘플링, 인덱스가 타임스탬프여야함.
# resample('M'): 월 단위로 데이터를 그룹핑
# first 메서드: 그룹핑한 데이터에서 첫번째를 대푯값으로 쓰겠다.

df.resample('MS').first() # S 옵션 추가: 그룹 중 가장 빠른 일자로 인덱스를 설정

how = {
    '시가':'first',
    '종가':'last',
    '고가':'max',
    '저가':'min',
    '거래량':'sum',
}
df.resample('MS').agg(how)

df.resample('3D').agg(how) # 3일단위로 그룹화. 시(H)/분(T)/초(S)/월(M)/일(D)

# 일/시/분/초에서는 S 옵션 안됨.
temp = df.resample('3D').agg(how)
temp.index=temp.index + pd.to_timedelta('2D') # Timedelta 객체로 시간 차이 보정하기. 모든 날짜에 2일차 시간 보정
temp.dropna() # dropna 메서드: 결측값 제거

df.resample('3D',offset='1D').agg(how) # resample 메서드의 offset 파라미터. 기준 일자를 조정. 1일 미루기.

df.resample('12H').agg(how) # 일봉 데이터를 12시간 단위의 데이터로 업샘플링

# 다운샘플링(Downsampling): 데이터 개수를 줄이는 것 (짧은 주기 → 긴 주기)
# 업샘플링(Upsampling): 데이터 개수를 늘리는 것 (긴 주기 → 짧은 주기)

df.resample('12H').agg(how).ffill() # ffill 메서드: 결측값을 이전 로우의 값으로 대체 (forward fill)
# bfill 메서드: 아래 행의 값으로 결측값 채워 넣음. backward fill

# NaN이 아니라 0으로 표시된다. sum 함수가 결측값을 0으로 합사하기 때문이다.

import numpy as np

temp = df.resample('12H').agg(how)
cond = temp.isna().any(axis=1)
# isna 메서드: NaN인 값은 True, 아닌 경우는 False 표기. 데이터프레임 반환
# ant 메서드: 하나라도 True면 True 반환. axis=1 옵션: 로우 단위로 비교
temp.loc[cond,'거래량']=np.nan # 하나라도 nan이 있는 행의 거래량을 nan으로 업데이트

temp.ffill()

"""6.6 수익률 계산하기"""

import pandas as pd

data = {'삼성전가':[52200, 52300, 52900, 52000, 51700],
        'LG전자':[68200,67800,68800,67500,66300]}
df=pd.DataFrame(data=data)
df.pct_change() # pct_change 메서드: 수익률 계산. pct=percent

# 하루 전이 아니라 2일 전에 사서 오늘 팔았을 때의 수익률 계산하기
print(df / df.shift(2) - 1) # shift 메서드로 수익률 직접 계산하기

print(df.pct_change(periods=2)) # pct_change 메서드의 periods 파라미터

#  보유 후 2일 뒤 매도하는 전략의 누적 수익률 계산하기
yeild = df.pct_change(periods=2)+1 # 인접한 두 값의 수익률을 얻어와서 원금 1을 더한 시리즈
yeild.cumprod() # cumprod 메서드: 시리즈에 대해서 누적곱 리턴

# 각 분기의 시가 대비 일일 상승률 계산하기
import pandas as pd

df=pd.read_csv("data_1724_20260718.csv", encoding="euc-kr", index_col=0, usecols=[0,1,4])
df.index=pd.to_datetime(df.index) # 날짜 칼럼을 데이터프레임 인덱스로 지정
df=df.sort_index() # 일자를 기준으로 오름차순으로 정렬
print(df.head())


df_quarter=df['시가'].resample('q').first().to_frame()
# resample 메서드: 시가칼럼에서 분기별로 데이터를 샘플링
# first 메서드: 샘플링된 각 그룹의 첫번째값 선택. 시리즈로 호출
# to_frame 메서드: 시리즈->데이터프레임
df_quarter

# Grouper 객체를 이용해서 분기별 데이터를 집계할 수도 있다.
df_quarter = df['시가'].groupby(pd.Grouper(freq='q')).first().to_frame()
df_quarter

# 수익률 계산하기 (분기별로 연결)
df_quarter['quarter']=df_quarter.index.quarter
df['quarter']=df.index.quarter

df_daily = df[['종가', 'quarter']].reset_index()
r = pd.merge(left=df_daily, right=df_quarter, on='quarter')
r

print(r.columns)

r['수익률']=r['종가']/r['시가']
r=r.set_index(['quarter','일자'])
r