# -*- coding: utf-8 -*-
"""ch07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTZdG3AoMFbvqfLQ5yPVjj3c7cInI_kY

7.1 pyplot 기초
"""

import matplotlib.pyplot as plt

fig = plt.figure() # Figure 클래스의 객체 생성
subplot = fig.add_subplot(1,1,1)
# 생성된 Figure 객체의 subplot(1,1,1)은 1행 1열의 액자에 첫번째 종이를 만든다.
# AxesSubplot 객체 반환
subplot.plot([1,2,3,4]) # AxesSubplot 객체에 그래프 그리기
plt.show() # 액자 보여주기

# 액자 = Figure 타입의 객체
# 종이 = AxesSubplot의 객체

import matplotlib.pyplot as plt

fig = plt.figure()
subplot1=fig.add_subplot(1,2,1) # 1행 2열 형태로 종이를 붙이고, 그 중 첫번째 종이
subplot2=fig.add_subplot(1,2,2) # 1행 2열 형태로 종이를 붙이고, 그 중 두번째 종이
subplot1.plot([1,2,3,4])
subplot2.plot([4,3,2,1])
plt.show()

fig, axes = plt.subplots(2,2)
axes[0][0].plot([1,2,3,4])
axes[0][1].plot([4,3,2,1])
axes[1][0].plot([1,2,2,1])
axes[1][1].plot([2,1,1,2])
plt.show()

plt.plot([1,2,3,4]) # 복잡한 설정 없이 간단한 그래프를 그릴 때. plot 함수
plt.show()

"""7.2 라인 차트

"""

# plot 함수로 리스트를 전달하면 y축으로 표기
# x축은 데이터를 전달하지 않으면 0부터 1씩 증가하는 정수값.

plt.plot([2,1,1,2])
plt.show
# (2,0) (1,1) (2,1) (3,2)

plt.plot([1,2,3,4],[2,1,1,2])
plt.xlabel("x-axis")
plt.ylabel('y-axis')
plt.title('matplotlib')
plt.show

# AxesSubplot 객체 이용해서 라벨과 타이틀 표시하기

fig, ax = plt.subplots()
ax.plot([1,2,3,4],[2,1,1,2])

ax.set_xlabel('x-axis')
ax.set_ylabel('y-axis')
ax.set_title('title')

plt.show()

# 한 번에 여러개 그리기

plt.plot([1,2,3,4],[1,2,3,4], label='ascending') # 헷갈릴 수 있으니 라벨 표시하기
plt.plot([1,2,3,4],[4,3,2,1], label='descending')

plt.legend(loc='best') # legend 함수. best 파라미터 : 최적의 위치에 범례를 표시한다.
plt.show()

import pandas as pd

kospi = pd.read_csv('data_1912_20260718.csv', encoding="cp949")
kospi

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt

plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

fig = plt.figure(figsize=(14,6))
ax = fig.add_subplot(1,1,1)
ax.plot(kospi['종가'])

ax.set_xlabel('날짜')
ax.set_ylabel('코스피지수')
ax.set_title('최근 6개월 동안 코스피 지수')
plt.grid(True, axis='y')
plt.show()

df = pd.read_excel('data/loan.xlsx', index_col=0, header=[0,1])
# header 파라미터: [0,1]을 사용해서 두 개의 행으로 멀티 컬럼 구성.
df.head()

대출잔액 =df['대출잔액']
대출잔액 = 대출잔액[::-1]
대출잔액.head()

fig = plt.figure(figsize=(12,8))
plt.plot(대출잔액.index, 대출잔액['전체'], marker='o',label='전체')
plt.plot(대출잔액.index, 대출잔액['1금융권'], marker='o',label='1금융권')
plt.plot(대출잔액.index, 대출잔액['2금융권'], marker='o',label='2금융권')

plt.rc('axes', unicode_minus=False) # y축 음수처리
plt.ylabel('(전년동월비,%)')
plt.legend()
plt.grid(True, axis='y')
plt.show()

"""7.3 막대 차트"""

plt.bar([1,3,5,7,9],[2,3,2,2,8])
plt.show()

kospi = pd.read_excel('data/kospi.xlsx', index_col='Date')
kospi2020=kospi.loc['2020']
mean_kospi_2020=kospi2020.resample('MS').mean() # 월별 평균 계산
mean_kospi_2020.head()

fig = plt.figure(figsize=(15,8))
ax = fig.add_subplot(1,1,1)
month = [x.strftime('%Y-%m') for x in mean_kospi_2020.index]
ax.bar(x = month, height=mean_kospi_2020['Volume'], width=0.5, color='skyblue')

plt.ticklabel_format(axis='y', style='plain') # 지수로 표현하지 않음
plt.title('KOSPI 월별 평균 거래량 (2020년)')
plt.xlabel('월')
plt.ylabel('평균 거래량')
plt.show()

fig = plt.figure(figsize=(15,8))
ax = fig.add_subplot(1,1,1)
month = [x.strftime('%Y-%m') for x in mean_kospi_2020.index]
ax.barh(y = month[::-1], width=mean_kospi_2020['Volume'][::-1], height=0.5, color='#F88878')

plt.ticklabel_format(axis='x', style='plain') # 지수로 표현하지 않음
plt.title('KOSPI 월별 평균 거래량 (2020년)')
plt.ylabel('월')
plt.xlabel('평균 거래량')
plt.show()

"""7.4 히스토그램"""

data = [1,2,2,3,3,3,4,4,4,4] # 1 1개, 2 2개, 3 3개, 4 4개
plt.hist(data)
plt.show()

# hist 함수: 입력 데이터를 구간으로 나눈 후 각 구간의 빈도수를 계산
# bins 파라미터로 값 전달 안하면 데이터를 10개의 구간으로 나눈다.
data =range(100) # 0~99
(n, bins, patches) = plt.hist(data)
plt.show()
# hist 함수는 튜플 객체를 리턴.

print(n) # 빈도수
print(bins) # 구간
print(patches) # 패치

kospi = pd.read_excel('data/kospi.xlsx', index_col='Date')
kospi.head()

n, bins, pathces = plt.hist(x=kospi['Change'] * 100, bins = 20)
# change 칼럼에 100을 곱하고, 20개 구간으로 나누어서 히스토그램 그리기
plt.grid()
plt.show()

"""7.5 지수화"""

sec = pd.read_excel('data/sec.xlsx', index_col='Date')
skhynix = pd.read_excel('data/skhynix.xlsx', index_col='Date')

fig = plt.figure(figsize=(12,8))
ax = fig.add_subplot(1,1,1)
ax.plot(sec.index, sec['Close'], label='SEC')
ax.plot(sec.index, skhynix['Close'], label='SK hynix')
plt.title('삼성전자, SK하이닉스 2020년 가격 비교')
plt.legend()
plt.show()

# indexing(지수화) : 정확히 비교하기 위해 두 종목을 같은 기준으로 스케일을 조정

# 비교 기간 동안 100에서 시작.

sec_index = (sec['Close'] / sec['Close'][0])* 100
skhynix_index = (skhynix['Close']/skhynix['Close'][0]) * 100

fig = plt.figure(figsize=(12,8))
ax = fig.add_subplot(1,1,1)
ax.plot(sec.index, sec_index, label='SEC')
ax.plot(sec.index, skhynix_index, label='SK hynix')
plt.ylabel('가격지수')
plt.title('삼성전자, SK하이닉스 2020년 가격 비교')
plt.legend()
plt.show()

"""7.6 캔들 차트"""

! pip install mplfinance

import mplfinance as mpf
mpf.__version__

import pandas as pd

df = pd.read_excel('data/sec.xlsx', index_col=0)
df.head()

import mplfinance as mpf

mpf.plot(data=df.loc['2020-12'], type='candle')

mpf.available_styles()

mc = mpf.make_marketcolors(
    up='r',
    down='b',
    edge='inherit', # 캔들의 몸통색
    wick='inherit', # 캔들의 머리/꼬리색
)

s = mpf.make_mpf_style(
    base_mpf_style='starsandstripes',
    marketcolors=mc,
    gridaxis='both', # horizontal, vertical, both
    y_on_right = True # False는 y축을 왼쪽에 표시
)

mpf.plot(data=df.iloc[:60],type='candle',style=s,figratio=(13,6))

mc = mpf.make_marketcolors(
    up='r',
    down='b',
    edge='inherit', # 캔들의 몸통색
    wick='inherit', # 캔들의 머리/꼬리색
    volume='inherit' # 거래량 색상
)

s = mpf.make_mpf_style(
    base_mpf_style='starsandstripes',
    marketcolors=mc,
    gridaxis='both', # horizontal, vertical, both
    y_on_right = True # False는 y축을 왼쪽에 표시
)

mpf.plot(
    data=df.iloc[:60],
    type='candle',
    style=s,
    figratio=(13,6),
    volume=True, # volume
    scale_width_adjustment=dict(volume=0.8, candle=1)
)

mpf.plot(
    data=df.iloc[:60],
    type='candle',
    mav = (5,20), # mav 파라미터: 이동평균. (5,20): 최근 5개와 20개 종가의 평균값
    style=s,
    figratio=(13,6),
    volume=True, # volume
    scale_width_adjustment=dict(volume=0.8, candle=1)
)

"""7.7 이동평균선"""

kospi = pd.read_excel('data/kospi.xlsx', index_col=0)
kospi["MA20"]=kospi['Close'].rolling(window=20).mean()
kospi["MA60"]=kospi['Close'].rolling(window=60).mean()
kospi["MA120"]=kospi['Close'].rolling(window=120).mean()
kospi.head()

fig = plt.figure(figsize=(14,6))
ax = fig.add_subplot(1,1,1)

ax.plot(kospi['Close'], label='close') # 종가
ax.plot(kospi['MA20'], label='MA20') # 20일 이동평균
ax.plot(kospi['MA60'], label='MA60') # 60일 이동평균
ax.plot(kospi['MA120'], label='MA120') # 120일 이동평균

ax.set_xlabel('date')
ax.set_ylabel('kospi')
ax.set_title('kospi')
ax.legend(loc='best') # loc='best'가 디폴트 값.
plt.grid(True, axis='y')
plt.show()

"""7.8 데이터프레임과 시각화"""

kospi = pd.read_excel('data/kospi.xlsx', index_col=0, usecols=[0,1,2])
kospi.head()
kospi.plot() # 데이터 프레임의 plot 메서드: 인덱스를 x축으로, 컬럼을 y 축으로. 여러개 컬럼-> 각각을 라인 차트로.

kospi.plot.line()
kospi.plot(kind='line')

upward = kospi['Open']<kospi['Close']
stationary = kospi['Open']==kospi['Close']
downward = kospi['Open']>kospi['Close']

kospi.loc[upward, 'category'] = 'upward'
kospi.loc[stationary, 'category'] = 'stationary'
kospi.loc[downward, 'category'] = 'downward'

how = {
    'category':len
}
data=kospi.groupby('category').agg(how)
print(data)

data.plot.bar(legend=False) # legend 파라미터: 범례의 표시 여부 설정