# -*- coding: utf-8 -*-
"""ch08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1noejbfmWnMzI-4UKIhS_HVczwwfnQF2r

8.1 주가지수
"""

import pandas as pd

df_13 = pd.read_excel('data/20210913.xlsx', index_col=0)
df_14 = pd.read_excel('data/20210914.xlsx', index_col=0)
print(len(df_13))
print(len(df_14))

# 행 단위로 한 종목의 가격 정보가 있다.
# 데이터 개수 = 종목의 수

# df_16 인덱스에 존재하지만 df_15 인덱스에 존재하지 않는 종목코드 출력하기
idx = df_14.index.difference(df_13.index) # difference 메서드: 호출한 객체에 포함되지 않은 값을 인덱스로 변환
print(idx)
print(df_14.loc[idx[0],'종목명'])

전일비교시가총액 = df_13['시가총액'].sum()
전일기준시가총액 = df_13['시가총액'].sum()
증감률 = (전일비교시가총액 +df_14.loc[idx[0], '시가총액']) / 전일비교시가총액
당일기준시가총액 = 증감률 * 전일기준시가총액
당일비교시가총액 = df_14['시가총액'].sum()
print(당일비교시가총액/당일기준시가총액) # 지수 상승률 출력 -> 약 0.67% 상승

# 주식 수가 변경된 종목이 있는지 확인하기
idx = df_14.index.intersection(df_13.index) # 교집합 티커를 인덱스 자료구조로 얻어오기
t_13 = df_13.loc[idx] # 공통된 티커만을 갖는 데이터프레임 선택
t_14 = df_14.loc[idx]
cond = t_13['상장주식수']!=t_14['상장주식수']
print(cond.all())

print(t_14.loc[cond,'상장주식수']-t_13.loc[cond,'상장주식수'])

주식수증가액 = (t_14.loc[cond,'상장주식수']-t_13.loc[cond,'상장주식수']) * t_13.loc[cond,'종가']
전일비교시가총액 = df_13['시가총액'].sum()
전일기준시가총액 = df_13['시가총액'].sum()
증감률 = (전일비교시가총액 + df_14.loc[idx[0], '시가총액'] + 주식수증가액.sum()) / 전일비교시가총액
당일기준시가총액 = 증감률 * 전일기준시가총액
당일비교시가총액 = df_14['시가총액'].sum()
print(당일비교시가총액 / 당일기준시가총액)

"""8.2 코스피와 삼성전자"""

import pandas as pd
df = pd.read_excel('data/20210914.xlsx', index_col=0)
df = df[['종목명', '종가', '시가총액']]

df = pd.read_excel('data/20210914.xlsx', index_col=0, usecols=[0,1,2,10]) # usecols 파라미터: 한 번에 필요한 컬럼 선택하기
df.head()

df['비중']=df['시가총액']/df['시가총액'].sum()*100
df.sort_values('비중', ascending=False).head() # 비중 컬럼을 내림차순으로 정렬

# 삼성전자와 코스피 지수의 유사도 파악하기
# 산포도

kospi = pd.read_excel('data/kospi.xlsx')
samsung = pd.read_excel('data/samsung.xlsx')

data =[kospi['종가'], samsung['종가']]
df = pd.concat(data, axis=1, keys=['kospi','samsung'])
# axis=1 -> 가로 방향으로 연결
# keys 파라미터:연결된 두 개의 컬럼 이름 지정하기
df.head()

df.plot.scatter(x='samsung',y='kospi')

# 상관관계 계산해서 유사도를 수치화하기
df.corr() # corr 메서드: 컬럼 단위로 상관관계를 계산함.

"""8.3 코스피의 통계"""

kospi = pd.read_excel('data/kospi.xlsx', index_col=0, parse_dates=True)
# 첫 번째 컬럼을 인덱스로 지정하며 인덱스를 문자열이 아닌 날짜로 해석한다.
# parse_dates 옵션 : 데이터를 읽으면서 날짜를 DatetimeIndex 객체로 변경한다.

print(kospi['종가'].max())
print(kospi['종가'].min())

cond = kospi['종가'] == kospi['종가'].max()
print(kospi.loc[cond]) # 행 전체를 출력

print(kospi.loc[cond].index)
print(kospi.loc[cond].index[0])

print(kospi['종가'].idxmax()) # 날짜만 출력
print(kospi['종가'].idxmin())

# 코스피 지수의 최대 상승폭과 최대 하락폭 5개씩 출력하기
kospi = pd.read_excel('data/kospi.xlsx', index_col=0, usecols=[0,1])
kospi['변동폭']=kospi['종가']-kospi['종가'].shift(1)
print(kospi.sort_values('변동폭').iloc[:5])
print(kospi.sort_values('변동폭', ascending=False).iloc[:5])

print(kospi['변동폭'].nlargest(n=5)) # nlargest 메서드로 간단히 표현하기
print(kospi['변동폭'].nsmallest(n=5)) # nsmallest 메서드로 간단히 표현하기

# 월별로 시가/고가/저가/종가/거래량 정리하기
kospi = pd.read_excel('data/kospi.xlsx', usecols=[0,1,4,5,6,7], parse_dates=[0])
how = {
    '시가':'first',
    '고가':'max',
    '저가':'min',
    '종가':'last',
    '거래량':'sum',
}
df = kospi.groupby(pd.Grouper(key='일자', freq='m')).agg(how)
df.head()

"""| 옵션                     | 의미                       | 추천도   |
| ---------------------- | ------------------------ | ----- |
| `parse_dates=[0]`      | 첫 번째 컬럼만 datetime으로 변환   | ⭐⭐⭐⭐⭐ |
| `parse_dates=['Date']` | 'Date' 컬럼만 datetime으로 변환 | ⭐⭐⭐⭐⭐ |
| `parse_dates=True`     | 날짜처럼 보이는 컬럼을 자동 변환       | ⭐⭐    |

"""

# 이벤트 정리하기
kospi = pd.read_excel('data/kospi.xlsx', usecols=[0,1], index_col=0, parse_dates=True)
kospi=kospi.sort_index()

threshold=2300 # 기준값, 임계값
cond=kospi['종가']>=threshold
print(kospi.loc[cond,'종가'].iloc[0])
print(kospi.loc[cond,'종가'].index[0])

# 반복문을 사용해서 전체 이벤트로 확장하기
for threshold in range(2300,3100,100):
  cond=kospi['종가']>=threshold
  print(threshold, kospi.loc[cond, '종가'].iloc[0], kospi.loc[cond,'종가'].index[0])

# 데이터를 리스트로 모아서 데이터프레임으로 변환하기
data =[]
for threshold in range(2300,3100,100):
  cond=kospi['종가']>=threshold
  data.append((f'{threshold} 포인트 돌파', kospi.index[cond][0], kospi.loc[cond, '종가'].iloc[0]))

df = pd.DataFrame(data, columns=['이벤트','일자','지수'])
df

"""8.4 코스피 수익률"""

kospi = pd.read_excel('data/kospi.xlsx', usecols = [0,1], index_col=0, parse_dates=True)
kospi=kospi.sort_index()
수익률 = kospi.iloc[-1,0]/kospi.iloc[0,0]
print((수익률-1)* 100)

# CAGR 계산하기
diff = (kospi.index[-1]-kospi.index[0])
투자기간 = diff.days / 365
cagr = 수익률 ** (1/투자기간) -1
print(cagr) # 연평균 26%의 수익률

# 보유 자산을 100% 삼전에 투자했다면?
ss = pd.read_excel('data/samsung.xlsx', usecols = [0,1], index_col=0, parse_dates=True)
ss=ss.sort_index()
수익률 = ss.iloc[-1,0]/ss.iloc[0,0]
diff = (ss.index[-1]-ss.index[0])
투자기간 = diff.days / 365
cagr = 수익률 ** (1/투자기간) -1
print(cagr) # 연평균 21%의 수익률

# 지수의 수익률 시각화하기
kospi_return = kospi['종가']/kospi.iloc[0,0]
ss_return = ss['종가']/ss.iloc[0,0]

df = pd.concat([kospi_return, ss_return], axis=1, keys=['kospi', 'samsung'])
df.index.name=''
df.plot(figsize=(12,5))

"""8.5 Maximum Drawdown"""

# MDD = 낙폭 중 최댓값

 import pandas as pd

 kospi = pd.read_excel('data/kospi2000.xlsx', index_col=0)
 kospi['전고점']=kospi['Close'].cummax()
 kospi['DD']=(1-kospi['Close']/kospi['전고점']) * 100
 kospi.head()

MDD = kospi['DD'].max()
print(MDD)

import matplotlib.pyplot as plt

plt.rc('axes', unicode_minus=False) # y축 음수처리

fig = plt.figure(figsize=(14,6))
ax1=fig.add_subplot(2,1,1)
ax2=fig.add_subplot(2,1,2)

ax1.plot(kospi.index, kospi['Close'], label='close')
ax2.plot(kospi.index, kospi['DD'] * -1, label='Drawdown')
ax2.fill_between(kospi.index, kospi['DD'] * -1, alpha = 0.1) # 색상채우기

ax1.grid()
ax2.grid()

ax1.legend(loc='best')
ax2.legend(loc='best')
plt.show()
