# -*- coding: utf-8 -*-
"""ch09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubvAFbdnRAWHDJA4NPiZluCGCmLabk7b
"""

! pip install finance-datareader

import FinanceDataReader as fdr

df = fdr.DataReader(symbol='005930')
df

df = fdr.DataReader(symbol='AAPL', start='2017')
df

kospi=fdr.DataReader(symbol='KS11', start='2000')
kosdaq=fdr.DataReader(symbol='KQ11', start='2000')
print(kospi)
print(kosdaq)