# -*- coding: utf-8 -*-
"""ch10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYZGDR9PtHZSewR7nPWcUy3Lk6xrFk4L

10.1 할로윈 투자 전략
"""

import pandas as pd

kospi = pd.read_excel('data/kospi.xlsx',index_col=0)
kospi.head()

kospi.loc['2000-11']
# 엑셀에는 날짜 포맷이 0번 컬럼.
# 바로 DatetimeIndex 처리됨.

kospi.loc['2001-04']

누적수익률 = 1
for year in range(2000,2021):
  buy_mon = str(year) + '-11'
  sell_mon = str(year+1) + '-04'
  # print(buy_mon, sell_mon)

  # 매수가
  매수가 = kospi.loc[buy_mon].iloc[0]['Open']

  # 매도가
  매도가 = kospi.loc[sell_mon].iloc[-1]['Close']

  # 수익률
  수익률 = 매도가/매수가
  누적수익률 = 누적수익률 * 수익률

print(누적수익률)

CAGR = (누적수익률 ** (1/21)) -1  # 투자기간 21년
CAGR * 100 # 약 9.06%

# 연평균 수익률 계산하기
단순보유누적수익률 = kospi.iloc[-1]['Close']/kospi.iloc[0]['Open']
단순보유CAGR=단순보유누적수익률 ** (1/21) -1
단순보유CAGR * 100 # 약 5.44%

"""10.2 할로윈 투자 전략 백테스팅"""

import datetime
from dateutil.relativedelta import relativedelta

start = datetime.datetime(year=2000, month=11, day=1)
end = start + relativedelta(months=5)

print(start.strftime('%Y-%m')) # 문자열로 변환
print(end.strftime('%Y-%m'))

def 투자6개월(df, start_year=2000, end_year=2020, month=11):

  for year in range(start_year, end_year):
    start = datetime.datetime(year=year, month=month, day=1)
    end = start + relativedelta(months=5)

    print(start.strftime('%Y-%m'), end.strftime('%Y-%m'))

투자6개월(None, start_year=2000, end_year=2020, month=12)

def 투자6개월(df, start_year=2000, end_year=2020, month=11):
  누적수익률=1

  for year in range(start_year, end_year):
    start = datetime.datetime(year=year, month=month, day=1)
    end = start + relativedelta(months=5)

    buy_mon = start.strftime('%Y-%m')
    sell_mon = end.strftime('%Y-%m')

    # 매수가
    매수가 = df.loc[buy_mon].iloc[0]['Open']

    # 매도가
    매도가 = df.loc[sell_mon].iloc[-1]['Close']

    # 수익률
    수익률 = 매도가 / 매수가
    누적수익률 = 누적수익률 * 수익률

  return 누적수익률

for month in range(1, 13):
    result = 투자6개월(
        kospi,
        start_year=2000,
        end_year=2021,
        month=month
    )
    print(f"{month}월 매수: {result:.4f}")

투자6개월(kospi, start_year=2000, end_year=2021, month=11)

"""10.3 할로윈 투자 전략 시각화"""

# 딕셔너리로 저장하기

data = {}

for month in range(1, 12+1):
  ret = 투자6개월(kospi, start_year=2000, end_year = 2021, month=month)
  data[month] = ret

print(data)

import matplotlib.pyplot as plt
import platform

fig = plt.figure(figsize=(15,8))
ax = fig.add_subplot(1,1,1)

ax.bar(
    x=list(data.keys()),
    height=list(data.values()),
    width=0.5,
    color='skyblue',
)