# -*- coding: utf-8 -*-
"""ch11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bX6jQY1Q9JOB4tM9151Weo1xaXUBdZyd

11.1 변동성 돌파 전략
"""

import pandas as pd

df = pd.read_excel('data/229200.xlsx', index_col='날짜')
df

"""11.2 변동성 돌파 전략 백테스팅"""

df['변동'] = df['고가'] - df['저가']
df.head()

df['전일변동'] = df['변동'].shift(1)
df.head()

df['목표가'] = df['시가'] + df['전일변동'] * 0.5
df.head()

import numpy as np

df['수익률']=np.where(df['고가']>=df['목표가'], df['종가']/df['목표가'], 1)
# np.where(조건, 참일 때 값, 거짓일 때 값)
df.head()

df['누적수익률'] = df['수익률'].cumprod()
df.tail()

delta = df.index[-1]-df.index[0]
year = delta.days / 365
CAGR = df['누적수익률'].iloc[-1] ** (1/year) -1
print('CAGR: ', CAGR * 100)

import matplotlib.pyplot as plt
import platform

fig = plt.figure(figsize = (14,6))
ax = fig.add_subplot(1,1,1)
ax.plot(df['누적수익률'], label='변동성돌파')
ax.plot(df['종가']/df['종가'].iloc[0], label='단순보유')

plt.show()

# MDD 계산하기
df['전고점'] = df['누적수익률'].cummax()
df['DD'] = (1-df['누적수익률']/df['전고점']) * 100
df.tail()

df['DD'].max()

import matplotlib.pyplot as plt

fig = plt.figure(figsize=(14,6))
ax=fig.add_subplot(1,1,1)

ax.plot(df.index, df['DD'] * -1)
ax.fill_between(df.index, df['DD'] * -1, alpha=0.1)
ax.grid()
plt.show()

"""11.3 마켓 타이밍"""

df['MA10']=df['종가'].rolling(window=10).mean()
df.head(n=10)

df['매매신호']=df['시가']>df['MA10'].shift(1)
df.head(20)

df['수익률2'] = np.where((df['매매신호']==1)&(df['고가']>=df['목표가']),
                      df['종가']/df['목표가'],
                      1)
df['누적수익률2']=df['수익률2'].cumprod()
print(df['누적수익률2'].iloc[-1])

fig = plt.figure(figsize=(14,6))
ax= fig.add_subplot(1,1,1)
ax.plot(df['누적수익률'], label='VB')
ax.plot(df['누적수익률2'], label='VBM')

plt.grid(True, axis='y')
plt.legend()
plt.show()

# DD 구하기
df['전고점2'] = df['누적수익률2'].cummax()
df['DD2']=(1-df['누적수익률2']/df['전고점']) * 100

fig = plt.figure(figsize=(14,6))
ax=fig.add_subplot(1,1,1)

ax.plot(df.index, df['DD'] * -1, label='VB')
ax.plot(df.index, df['DD2'] * -1, label='VBM')

ax.grid()
plt.xlabel('Date')
plt.ylabel('Drawdown')
plt.legend()
plt.show()